version: '3'

services:

  postgresql:

    image: postgres:16.2

    environment:
      POSTGRES_DB: beauty_plaza
      POSTGRES_PASSWORD: password_tqs

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 15s
      retries: 5

    restart: unless-stopped

    volumes: 
      - pg_data:/var/lib/postgresql/data

    networks:
      - backend

  backend:

    depends_on:
      postgresql:
        condition: service_healthy

    build: 
      context: ./backend
      dockerfile: Dockerfile

    container_name: "beauty_plaza_backend"

    restart: unless-stopped

    volumes:
      - ./backend:/backend

    ports:
      - 8080:8080
    
    networks:
      - backend

  customer_portal_app:

    depends_on:
      - backend

    build: 
      context: ./customer_app
      dockerfile: Dockerfile

    container_name: "beauty_plaza_customer_portal"

    restart: unless-stopped

    volumes:
      - ./customer_app:/customer_app

    ports:
      - 3001:3001

    networks:
      - frontend

  staff_portal_app:

    depends_on:
      - backend

    build: 
      context: ./staff_app
      dockerfile: Dockerfile

    container_name: "beauty_plaza_staff_portal"

    restart: unless-stopped

    volumes:
      - ./staff_app:/staff_app
    
    ports:
      - 3002:3002

    networks:
      - frontend

  screens_app:

    depends_on:
      - backend

    build:
      context: ./digital_screen
      dockerfile: Dockerfile
    
    container_name: "beauty_plaza_screens"

    restart: unless-stopped

    volumes:
      - ./digital_screen:/digital_screen

    ports:
      - 3003:3003

    networks:
      - frontend

volumes:
  pg_data:

networks:

  backend:
    driver: bridge

  frontend:
    driver: bridge

    
